### ISSUE TITLE
Start and end positions swapped.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/normalizer#12]
When the following request is done to the API:

    curl -X GET "http://v3.mutalyzer.nl/api/reference_model/NM_002001.2" -H  "accept: application/json"

we get the following response:

    "model": {
      "id": "NM_002001.2",
      "type": "record",
      "location": {
        "type": "range",
        "start": {
          "type": "point",
          "position": 1191
        },
        "end": {
          "type": "point",
          "position": 0
        }
      },
    ...

The `start` and `end` positions seem to be swapped.

**Comment by mihailefter** [comment]
Solved in the [retriever](https://github.com/mutalyzer/retriever/commit/d304af674cab4999681c045daa90fc1c176b6f38).
