### ISSUE TITLE
`get_selectors` does not work for chromosomes.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/normalizer#13]
The following request:

    curl -X GET "http://v3.mutalyzer.nl/api/get_selectors/NC_000001.11" -H  "accept: application/json"

results in an `ERETR` error. It is unclear why.

**Comment by mihailefter** [comment]
The `get_selectors` endpoint works also for chromosomes, but the `ERETR` is raised if the source is down or there is any other connection error.
