### ISSUE TITLE
Position converter not working for chromosomes.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/normalizer#18]
One of the [examples](http://v3.mutalyzer.nl/positionconverter?referenceId=NC_000001.11&fromSelectorId=NM_001232.4&fromCoordinateSystem=Selector&position=274&toSelectorId=&toCoordinateSystem=&includeOverlapping=false) results in an `ERETR` error.

**Comment by mihailefter** [comment]
Works now. I remember that the NCBI was down for some time at that time.
