### ISSUE TITLE
Missing affected transcripts.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/normalizer#27]
For the following description:

    NC_000016.9:g.15815278C>T

No affected transcripts were found, while Mutalyzer 2 [finds](https://mutalyzer.nl/name-checker?description=NC_000016.9%3Ag.15815278C%3ET) 13.

**Comment by mihailefter** [comment]
It seems like the retrieved gff3 file contains no features. I'll contact the NCBI.

**Comment by mihailefter** [comment]
It seems like the GRCh37 gff3 files retrieved using eutils do not contain the annotation. Upon contacting the NCBI, they recommended to retrieve the gff3 for the entire GRCh37 assembly from [here][1. Next, we extract the chromosomes and populate the cache. Another suggested method requires the use of [NCBI Datasets][2] (under development):

    ./datasets download genome accession GCF_000001405.25 --exclude-seq --exclude-rna --exclude-protein --filename GRCh37-annot.zip

[1]: https://ftp.ncbi.nlm.nih.gov/genomes/archive/old_refseq/Homo_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_GRCh37.p13_top_level.gff3.gz
[2]: https://www.ncbi.nlm.nih.gov/datasets/

**Comment by jfjlaros** [comment]
Which approach was chosen to resolve this issue?

**Comment by mihailefter** [comment]
For the moment, the first one.

**Comment by jfjlaros** [comment]
That is clear, thanks.
