### ISSUE TITLE
there are some errors in readme.md

### ISSUE THREAD

**Issue by fengfeng0918** [mutalyzer/normalizer#40]
> git checkout refactor
- The refactor branch don't exist. Does it have matter?

>git clone git@git.lumc.nl:mlefter/mutalyzer-visualization-vuetify.git 
-  it seem to be a private repository. Could it be shared?

thanks!

**Comment by mihailefter** [comment]
Thanks for the notice @fengfeng0918.

There is no need any longer to checkout `refactor`.

The current front-end repository is the following:
https://github.com/mutalyzer/website

We'll update the README accordingly.
