### ISSUE TITLE
3' rule  don't apply to some hgvs.g

### ISSUE THREAD

**Issue by fengfeng0918** [mutalyzer/normalizer#41]
`NC_000012.11:g.78582566_78582568delinsGATAA` should be normalized to  `NC_000012.11:g.78582569_78582571delinsGATAA`

**Comment by jfjlaros** [comment]
It should not.

In the [first](https://mutalyzer.nl/name-checker?description=NC_000012.11%3Ag.78582566_78582568delinsGATAA) description, the first `AAT` unit is replaced with `GATAA`, in the [second](https://mutalyzer.nl/name-checker?description=NC_000012.11%3Ag.78582569_78582571delinsGATAA) description, the second unit is affected.
