### ISSUE TITLE
Missing warning messages.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/normalizer#5]
The following descriptions are (rightfully) silently corrected. However a warning about why they were corrected would be in order.

    NG_012337.1:g.7125+1G>T
    NG_012337.1:g.7125G>TA

For the first description I would expect a warning about using an intronic position without a proper exon boundary.
For the second description I would expect a warning about the type (operator) used.

**Comment by mihailefter** [comment]
- `NG_012337.1:g.7125+1G>T` raise an error that an offset was used in combination with a genomic coordinate system.
- `NG_012337.1:g.7125G>TA` convert to a `delins` and let the user know.
